spring:
  profiles:
    active: local


#local
---
spring:
  profiles: local
#  datasource:
#  url: jdbc:h2:tcp://localhost/~/demomarket
#  username: sa
#  password:
#  driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace